### ISSUE TITLE
Server Chest Opening Delay for my friend

### ISSUE THREAD

**Issue by BobRossChan** [FTBTeam/FTB-Interactions#688]
## Modpack Version: 
1.7.10

## Bug Report:
So me and my friends are playing on our server everyone is running smoothly and then my friend (KnotFerdy) can move just fine no frame lag, but has a 40 second delay in opening chests and seeing the others movements. Now everyone else on the server doesnt have this problem and I don't think it has to do with ping because when i look at console it is just spewing out red errors.

## Expected Behavior/Suggestions:
Friend (KnotFerdy) joins server attempts to open chest, open team menu etc. has a ~40 second delay opening these.

Intended Behavior: No delay when opening a chest.

## Is It Repeatable? Steps to Reproduce: 

1. Join server
2. Open chest or team menu
3. Wait 40 seconds and container/menu opens

## Link to Log or Crash File Paste**: 
Ok so the server log is 63mb and when I try to past to the paste my whole log the the site crashes but the error that is spammed over and over again is

[12:02:08] [Netty Server IO #3/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_171]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_171]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_171]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [minecraft_server.1.12.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[12:02:08] [Netty Server IO #3/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_171]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_171]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_171]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [minecraft_server.1.12.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[12:02:08] [Netty Server IO #3/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_171]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_171]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_171]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [minecraft_server.1.12.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[12:02:08] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: KnotFerdy left the game
[12:02:08] [Netty Server IO #3/ERROR] [FML]: NetworkDispatcher exception

Thank you for your time!

**Comment by BobRossChan** [comment]
Also something to add is when hosting on the same computer but a vanilla server he has no issues

**Comment by Dimmerworld** [comment]
Having the same issue, but also weird bandwidth issues, whenever I'm in my base, my download peaks at 30mbps constantly but when I go to spawn it's back to normal. Whilst everyone else is 
![Capture](https://user-images.githubusercontent.com/4002351/59403728-25a45800-8de7-11e9-85f7-1ef54fd4a0c7.PNG)
lag-free mostly.

**Comment by Saereth** [comment]
gregtech sends a ton of nbt data until it catches up then it should lower, try segmenting your processes with compact machines. The log file shows network connectivity issues there with the original chest issue.

**Comment by Saereth** [comment]
nothing we can do here, gtce knows the issue, they've done some to mitigate but not enough imo, either way its out of our hands so closing this issue
