### ISSUE TITLE
Astral Sorcery crashing when launched through Steam

### ISSUE THREAD

**Issue by starlingfire** [FTBTeam/FTB-Interactions#697]
FTB Interactions crashes when I try to launch it through Steam for In-Home streaming. I understand this is outside the scope of the team, but I cannot seem to find any useful information about this crash and am hoping someone can provide some insight.

The culprit seems to be Astral Sorcery. Here is a snippet, though full crash report is linked below:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Astral Sorcery (astralsorcery)
Caused by: java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader.initReaderIDs(Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;)V
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.initReaderIDs(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.<clinit>(JPEGImageReader.java:96)
	at com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(JPEGImageReaderSpi.java:85)
	at javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:529)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:513)
	at javax.imageio.ImageIO.read(ImageIO.java:1443)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)
```

## Modpack Version: 
1.4.1 and 1.7.0

## Bug Report:
Launching the game works fine through the Minecraft launcher directly, but crashes when trying to launch through Steam as a manually-added game.

## Expected Behavior/Suggestions:
I would expect this to launch normally.

## Is It Repeatable? Steps to Reproduce: 
https://youtu.be/e0dKcBwt9lE

## Link to Log or Crash File Paste: 
https://paste.feed-the-beast.com/view/e1f52546

## Mod/s Affected: 
Astral Sorcery

## Attempted Fixes (none known to work): 
* Disabled FoamFix mod
* Disabled Discord mod
* Removed all dimensions from Astral Sorcery's skySupportedDimensions and weakSkyRenders
* Removed all custom java parameters except RAM allocation

## System Setup
* Solus linux x64
* Nvidia 1080 Ti w/drivers 430.14
* Intel i7-7700K

**Comment by Saereth** [comment]
please report this to astral sorcery, not only is it outside the scope of the pack theres literally nothing we can do about it.
