### ISSUE TITLE
updated to beta 1.9 crashing to desktop upon attempted world load

### ISSUE THREAD

**Issue by dcirusc36** [FTBTeam/FTB-Interactions#724]
## Bug Report: 
updated to 1.9 beta version of the pack crashing to desktop here is a crashlog/report https://pastebin.com/xbGADdj0 

## Expected Behavior/Suggestions:
for my world to load after updating.....
read above^^

## Is It Repeatable? Steps to Reproduce: 

1.update pack from 1.8.2beta to 1.9beta
2.launch pack choose existing world = crash

## Link to Log or Crash File Paste**: 
https://pastebin.com/xbGADdj0

## Mod/s Affected: 
zen triggers seems to be main mod affected. Zen Summoning-1.12-1.0.16 

## Known Fix: 
not a fix more of a work around. downgraded zen summoning-1.12-1.0.16 to 1.12-10.15 and i can load my world. 
update: ok so i just got into my world the dimension/void you start in works fine (with zen summoning-1.12-1.0.15) i went to the overworld walked around for a bit seemed fine until i looked a certain direction and crashed don't know what caused it cause no mobs were about and it was daytime.

**Comment by mfkG** [comment]
same here
https://pastebin.com/BFNDTXsk

**Comment by HavicDave20** [comment]
Having same issue, even created new world got to over world, 2nd time through game crashed and when logging back into world it continues to crash gives:

Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.ArrayList.forEach(Unknown Source)
	at zentriggers.zentriggers.Handler.onTick(Handler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1230_Handler_onTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

**Comment by ZeekDaGeek** [comment]
I was having a similar issue on the server side that caused my server to crash. Try going into `./scripts/ZenEvents.zs` and change `Handler.onEntityUpdateRaw` to `Handler.onEntityUpdate` and see if the world loads.

I'm sure this will break whatever it's trying to fix, however, the world will at least load and give you the same state as 1.8.2.

**Comment by DictatorBob** [comment]
ZeekDaGeek's workaround works, but I still get occasional crashes when teleporting, and a lot of what seems like chunk loading lag. I've reverted to 1.8.2. :(
