### ISSUE TITLE
Super Factory Manager server bug

### ISSUE THREAD

**Issue by SirQuacker** [FTBTeam/FTB-Interactions#835]
## Bug Report:
getting error for super factory manager when clicking on any function
## Expected Behavior/Suggestions:
when function clicked on game freezes and console prints the following

[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]: java.lang.reflect.InvocationTargetException
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at sun.reflect.GeneratedConstructorAccessor312.newInstance(Unknown Source)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at java.lang.reflect.Constructor.newInstance(Unknown Source)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at vswe.superfactory.components.FlowComponent.<init>(FlowComponent.java:142)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at vswe.superfactory.tiles.TileEntityManager$ButtonCreate.onClick(TileEntityManager.java:799)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at vswe.superfactory.tiles.TileEntityManager.readGenericData(TileEntityManager.java:615)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at vswe.superfactory.tiles.TileEntityManager.readUpdatedData(TileEntityManager.java:598)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at vswe.superfactory.network.packets.PacketEventHandler.processServerPacket(PacketEventHandler.java:80)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at vswe.superfactory.network.packets.PacketEventHandler.lambda$onServerPacket$1(PacketEventHandler.java:61)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at java.util.concurrent.FutureTask.run(Unknown Source)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at java.lang.Thread.run(Unknown Source)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchMethodError: vswe.superfactory.components.ComponentMenuStuff.updateSearch(Ljava/lang/String;Z)Ljava/util/List;
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at vswe.superfactory.components.ComponentMenuStuff$3.getSearchResults(ComponentMenuStuff.java:118)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at vswe.superfactory.components.ScrollController.getSearchResults(ScrollController.java:80)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at vswe.superfactory.components.ScrollController.<init>(ScrollController.java:75)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at vswe.superfactory.components.ScrollController.<init>(ScrollController.java:53)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at vswe.superfactory.components.ComponentMenuStuff$3.<init>(ComponentMenuStuff.java:111)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at vswe.superfactory.components.ComponentMenuStuff.<init>(ComponentMenuStuff.java:111)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at vswe.superfactory.components.ComponentMenuFluid.<init>(ComponentMenuFluid.java:25)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     ... 17 more
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]: java.lang.reflect.InvocationTargetException
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at sun.reflect.GeneratedConstructorAccessor312.newInstance(Unknown Source)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at java.lang.reflect.Constructor.newInstance(Unknown Source)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at vswe.superfactory.components.FlowComponent.<init>(FlowComponent.java:142)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at vswe.superfactory.components.FlowComponent.copy(FlowComponent.java:1257)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at vswe.superfactory.interfaces.ContainerManager.func_75142_b(ContainerManager.java:61)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.world.World.func_72866_a(World.java:1993)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.world.World.func_72870_g(World.java:1955)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.world.World.func_72939_s(World.java:1734)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[23:15:59] [Server thread/INFO] [STDERR]: [vswe.superfactory.components.FlowComponent:<init>:147]:      at java.lang.Thread.run(Unknown Source)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchMethodError: vswe.superfactory.components.ComponentMenuStuff.updateSearch(Ljava/lang/String;Z)Ljava/util/List;
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at vswe.superfactory.components.ComponentMenuStuff$3.getSearchResults(ComponentMenuStuff.java:118)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at vswe.superfactory.components.ScrollController.getSearchResults(ScrollController.java:80)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at vswe.superfactory.components.ScrollController.<init>(ScrollController.java:75)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at vswe.superfactory.components.ScrollController.<init>(ScrollController.java:53)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at vswe.superfactory.components.ComponentMenuStuff$3.<init>(ComponentMenuStuff.java:111)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at vswe.superfactory.components.ComponentMenuStuff.<init>(ComponentMenuStuff.java:111)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at vswe.superfactory.components.ComponentMenuFluid.<init>(ComponentMenuFluid.java:25)
[23:15:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     ... 18 more

## Is It Repeatable? Steps to Reproduce: 
https://share.wildbook.me/mWsCDVqODX4bq0Mm.mp4

## Mod/s Affected: 
super factory manager

**Comment by Saereth** [comment]
Please report here: https://github.com/TeamDman/SuperFactoryManager/issues
@TeamDman ! :P

**Comment by TeamDman** [comment]
Looks like a manager is attempting to perform a search (client side operation) on the server side. The most likely cause of this is an update to the manager's NBT schema that happened between two previous versions of the mod has corrupted the manager. Breaking and replacing it _should_ fix the issue...

**Comment by Saereth** [comment]
referred to SFM tracker but could reproduce
